---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

- name: ccp-7
  type: docker-image
  source:
    repository: pivotaldata/ccp
    tag: 7

- name: ccp_src
  type: git
  source:
    branch: {{ccp-git-branch}}
    private_key: {{ccp-git-key}}
    uri: {{ccp-git-remote}}

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}

- name: pxf_src
  type: git
  source:
    branch: {{pxf-git-branch}}
    uri: {{pxf-git-remote}}
    private_key: ((ccp-git-key))

- name: gpdb-pxf-dev-centos7
  type: docker-image
  source:
    repository: pivotaldata/gpdb-pxf-dev
    tag: centos7

- name: gpdb6-centos7-build
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-build

- name: gpdb-pxf-dev-centos7-hdp2-server
  type: docker-image
  source:
    repository: pivotaldata/gpdb-pxf-dev
    tag: centos7-hdp2-server

# ~/workspace/gp-continuous-integration/secrets/gpdb6-integration-testing.dev.yml
- name: libquicklz-centos7
  type: gcs
  source:
    bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
    json_key: ((gp-internal-artifacts-service-account-key))
    regexp: centos7/libquicklz-(\d.*)\.el7\.x86_64\.rpm

- name: python-centos7
  type: gcs
  source:
    bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
    json_key: ((gp-internal-artifacts-service-account-key))
    versioned_file: centos7/python-2.7.12.tar.gz

- name: libquicklz-devel-centos7
  type: gcs
  source:
    bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
    json_key: ((gp-internal-artifacts-service-account-key))
    regexp: centos7/libquicklz-devel-(\d.*)\.el7\.x86_64\.rpm

- name: libsigar-centos7
  type: gcs
  source:
    bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
    json_key: ((gp-internal-artifacts-service-account-key))
    regexp: centos7/sigar-rhel7_x86_64-(.*)\.targz

- name: pxf_tarball
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: pxf_artifacts/((folder-prefix))_((gpdb-branch))/latest/pxf.tar.gz

- name: bin_gpdb
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: pxf_artifacts/((folder-prefix))_((gpdb-branch))/latest/bin_gpdb.tar.gz

# anchors
ccp_destroy_anchor: &ccp_destroy
  do:
  - put: terraform_gpdb
    resource: terraform
    params:
      action: destroy
      env_name_file: terraform_gpdb/name
      terraform_source: ccp_src/google/
    get_params:
      action: destroy

dataproc_destroy_anchor: &dataproc_destroy
  do:
  - aggregate:
    - task: cleanup_dataproc
      config:
        run:
          path: pxf_src/concourse/scripts/cleanup_dataproc_cluster.bash
        inputs:
          - name: pxf_src
          - name: dataproc_env_files
        platform: linux
      image: ccp-7
      params:
        GOOGLE_CREDENTIALS: {{google-service-account-key}}
        GOOGLE_ZONE: {{google-zone}}
    - put: terraform_gpdb
      resource: terraform
      params:
        action: destroy
        env_name_file: terraform_gpdb/name
        terraform_source: ccp_src/google/
      get_params:
        action: destroy

dataproc_timed_destroy_anchor: &dataproc_timed_destroy
  do:
  - task: debug_sleep
    image: ccp-7
    config:
      run:
        path: /bin/sleep
        args: [{{dataproc-destroy-timeout}}]
      platform: linux
  - task: cleanup_dataproc
    config:
      run:
        path: pxf_src/concourse/scripts/cleanup_dataproc_cluster.bash
      platform: linux
      inputs:
        - name: pxf_src
        - name: dataproc_env_files
    image: ccp-7
    params:
      GOOGLE_CREDENTIALS: {{google-service-account-key}}
      GOOGLE_ZONE: {{google-zone}}

jobs:

- name: compile_pxf
  plan:
  - get: pxf_src
    trigger: true
  - aggregate:
    - get: gpdb_src
      trigger: true
    - get: gpdb-pxf-dev-centos7
  - task: compile_pxf
    image: gpdb-pxf-dev-centos7
    file: pxf_src/concourse/tasks/compile_pxf.yml
  - put: pxf_tarball
    params: { file: pxf_artifacts/pxf.tar.gz }

- name: compile_gpdb
  plan:
  - aggregate:
    - get: gpdb_src
      params: { submodules: all, submodules_recursive: true }
      trigger: true
    - get: gpdb6-centos7-build
    - get: libquicklz-installer
      resource: libquicklz-centos7
    - get: python-tarball
      resource: python-centos7
    - get: libquicklz-devel-installer
      resource: libquicklz-devel-centos7
    - get: libsigar-installer
      resource: libsigar-centos7
  - task: compile_gpdb_centos7
    file: gpdb_src/concourse/tasks/compile_gpdb.yml
    image: gpdb6-centos7-build
    params:
      CONFIGURE_FLAGS: '--enable-cassert --enable-debug-extensions'
      TARGET_OS: centos
      TARGET_OS_VERSION: 7
      BLD_TARGETS: "clients loaders"
    timeout: 30m
  - put: bin_gpdb
    params: { file: gpdb_artifacts/bin_gpdb.tar.gz }

- name: test_pxf
  plan:
  - aggregate:
    - get: pxf_src
      passed:
        - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
        - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
        - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
        - compile_pxf
        - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
        - name: gpdb_src
        - name: bin_gpdb
        - name: pxf_src
        - name: pxf_tarball
      params:
        IMPERSONATION: true
        TARGET_OS: centos
        TARGET_OS_VERSION: 7
        HADOOP_CLIENT: HDP
        GROUP: smoke_schedule,fdw_smoke_schedule
        PG_REGRESS: true
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_s3
  plan:
  - aggregate:
    - get: pxf_src
      passed:
        - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
        - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
        - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
        - compile_pxf
        - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
        - name: gpdb_src
        - name: bin_gpdb
        - name: pxf_src
        - name: pxf_tarball
      params:
        IMPERSONATION: true
        TARGET_OS: centos
        TARGET_OS_VERSION: 7
        HADOOP_CLIENT: HDP
        GROUP: hcfs_schedule,fdw_hcfs_schedule
        PG_REGRESS: true
        PROTOCOL: s3
        ACCESS_KEY_ID: {{tf-machine-access-key-id}}
        SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_gcs
  plan:
  - aggregate:
    - get: pxf_src
      passed:
        - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
        - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
        - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
        - compile_pxf
        - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
        - name: gpdb_src
        - name: bin_gpdb
        - name: pxf_src
        - name: pxf_tarball
      params:
        IMPERSONATION: true
        TARGET_OS: centos
        TARGET_OS_VERSION: 7
        HADOOP_CLIENT: HDP
        GROUP: hcfs_schedule,fdw_hcfs_schedule
        PG_REGRESS: true
        PROTOCOL: gs
        GOOGLE_CREDENTIALS: {{data-gpdb-ud-google-json-key}}
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_wasbs
  plan:
  - aggregate:
    - get: pxf_src
      passed:
        - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
        - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
        - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
        - compile_pxf
        - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
        - name: gpdb_src
        - name: bin_gpdb
        - name: pxf_src
        - name: pxf_tarball
      params:
        IMPERSONATION: true
        TARGET_OS: centos
        TARGET_OS_VERSION: 7
        HADOOP_CLIENT: HDP
        GROUP: hcfs_schedule,fdw_hcfs_schedule
        PG_REGRESS: true
        PROTOCOL: wasbs
        WASBS_ACCOUNT_NAME: {{wasb-account-name}}
        WASBS_ACCOUNT_KEY: {{wasb-account-key}}
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_adl
  plan:
  - aggregate:
    - get: pxf_src
      passed:
        - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
        - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
        - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
        - compile_pxf
        - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
        - name: gpdb_src
        - name: bin_gpdb
        - name: pxf_src
        - name: pxf_tarball
      params:
        IMPERSONATION: true
        TARGET_OS: centos
        TARGET_OS_VERSION: 7
        HADOOP_CLIENT: HDP
        GROUP: hcfs_schedule,fdw_hcfs_schedule
        PG_REGRESS: true
        PROTOCOL: adl
        ADL_ACCOUNT: {{adl-account}}
        ADL_OAUTH2_CLIENT_ID: {{adl-client-id}}
        ADL_OAUTH2_CREDENTIAL: {{adl-credential}}
        ADL_OAUTH2_REFRESH_URL: {{adl-refresh-url}}
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_minio
  plan:
  - aggregate:
    - get: pxf_src
      passed:
        - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
        - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
        - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
        - compile_pxf
        - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    file: pxf_src/concourse/tasks/test_pxf.yml
    image: gpdb-pxf-dev-centos7-hdp2-server
    params:
      GROUP: hcfs_schedule,fdw_hcfs_schedule
      PG_REGRESS: true
      IMPERSONATION: false
      PROTOCOL: minio
      TARGET_OS: centos
      TARGET_OS_VERSION: 7

- name: test_pxf_secure_multinode_gpdb
  max_in_flight: 2
  plan:
  - aggregate:
    - get: ccp_src
    - get: gpdb_src
      passed:
        - compile_pxf
        - compile_gpdb
    - get: bin_gpdb
      passed:
        - compile_gpdb
    - get: pxf_src
      passed:
        - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
        - compile_pxf
      trigger: true
    - get: ccp-7
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - aggregate:
    - do:
      - put: terraform_gpdb
        resource: terraform
        params:
          action: create
          delete_on_failure: true
          generate_random_name: true
          terraform_source: ccp_src/google/
          vars:
            PLATFORM: centos7
            number_of_nodes: {{number_of_gpdb_nodes}}
            segments_per_host: 4
            instance_type: n1-standard-4
            ccp_reap_minutes: 120
      - task: Generate Greenplum Cluster
        input_mapping:
          terraform: terraform_gpdb
        file: ccp_src/ci/tasks/gen_cluster.yml
        image: ccp-7
        params:
          AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
          AWS_DEFAULT_REGION: {{aws-region}}
          BUCKET_PATH: {{tf-bucket-path}}
          BUCKET_NAME: {{tf-bucket-name}}
          PLATFORM: centos7
          CLOUD_PROVIDER: google
      - task: intialize_greenplum
        file: ccp_src/ci/tasks/gpinitsystem.yml
    - task: Generate Hadoop Cluster
      file: pxf_src/concourse/tasks/install_dataproc.yml
      image: ccp-7
      params:
        GOOGLE_CREDENTIALS: {{google-service-account-key}}
        GOOGLE_PROJECT_ID: {{google-project-id}}
        GOOGLE_ZONE: {{google-zone}}
        IMAGE_VERSION: {{dataproc-image-version}}
        KERBEROS: {{kerberos-enabled}}
  - task: setup_pxf
    input_mapping:
      terraform: terraform_gpdb
      bin_gpdb: gpdb_binary
    file: pxf_src/concourse/tasks/install_pxf.yml
    image: ccp-7
    params:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      AWS_DEFAULT_REGION: {{aws-region}}
      BUCKET_PATH: {{tf-bucket-path}}
      BUCKET_NAME: {{tf-bucket-name}}
      CLOUD_PROVIDER: google
      IMPERSONATION: {{enable-impersonation-multinode}}
      INSTALL_GPHDFS: false
      KERBEROS: {{kerberos-enabled}}
      PLATFORM: centos7
      PXF_JVM_OPTS: {{pxf-jvm-opts}}
    on_failure:
      <<: *dataproc_timed_destroy
  - task: test_pxf_multinode
    input_mapping:
      bin_gpdb: gpdb_binary
    on_success:
      <<: *dataproc_destroy
    on_failure:
      <<: *dataproc_timed_destroy
    image: gpdb-pxf-dev-centos7-hdp2-server
    file: pxf_src/concourse/tasks/test_pxf_multinode.yml
    params:
      ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      HIVE_VERSION: 2
      IMPERSONATION: {{enable-impersonation-multinode}}
      KERBEROS: {{kerberos-enabled}}
      GROUP: smoke_schedule,fdw_smoke_schedule
      PG_REGRESS: true
      PXF_JVM_OPTS: {{pxf-jvm-opts}}
      TARGET_OS: centos
