platform: linux
image_resource:
  type: docker-image
inputs:
  - name: pxf_src
outputs:
  - name: dataproc_env_files
params:
  GOOGLE_CREDENTIALS:
  GOOGLE_PROJECT_ID:
  GOOGLE_ZONE:
  GOOGLE_SERVICE_ACCOUNT:
  PLATFORM: centos7
  CLOUD_PROVIDER: google
  ENV_FILES_DIR: dataproc_env_files
  IMAGE_VERSION: 1.3
  INITIALIZATION_SCRIPT:
  KERBEROS: false
  KEYRING:
  KEY:
  PROJECT:
  REGION: us-central1
  SECRETS_BUCKET:
  SUBNETWORK: dynamic
  ZONE: us-central1-a
run:
path: pxf_src/concourse/scripts/create_dataproc_cluster.bash
